# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1
[default.deploy.parameters]
stack_name = "CalculatorapiNative"
s3_prefix = "CalculatorapiNative"
resolve_s3 = true
region = "us-east-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []